<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>JLib.ValueTypes.Mapping</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JLib.Reflection\JLib.Reflection.csproj" />
    <ProjectReference Include="..\JLib.ValueTypes\JLib.ValueTypes.csproj" />
  </ItemGroup>

</Project>

