<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>

    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />

    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JLib.Configuration\JLib.Configuration.csproj" />
    <ProjectReference Include="..\JLib.Exceptions\JLib.Exceptions.csproj" />
    <ProjectReference Include="..\JLib.Helper\JLib.Helper.csproj" />
    <ProjectReference Include="..\JLib.Reflection\JLib.Reflection.csproj" />
  </ItemGroup>

</Project>

