<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\JLib.AutoMapper\JLib.AutoMapper.csproj" />
      <ProjectReference Include="..\JLib.DataGeneration\JLib.DataGeneration.csproj" />
      <ProjectReference Include="..\JLib.Reflection.DependencyInjection\JLib.Reflection.DependencyInjection.csproj" />
    </ItemGroup>

</Project>

