<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JLib.SystemTextJson\JLib.SystemTextJson.csproj" />
    <ProjectReference Include="..\JLib.Testing\JLib.Testing.csproj" />
  </ItemGroup>
</Project>
