using System.Diagnostics.CodeAnalysis;

using JLib.Helper;
using JLib.ValueTypes;

namespace JLib.DataGeneration;

/// <summary>
/// contains additional information about an id which has been generated by the <see cref="IIdRegistry"/>.
/// </summary>
public struct IdSnapshotInformation : IComparable<IdSnapshotInformation>
{
    internal IdSnapshotInformation(DataPackageValues.IdIdentifier idIdentifier, object? value, bool includeValue = false)
    {
        this.IdGroupName = idIdentifier.IdGroupName.Value;
        this.IdName = idIdentifier.IdName.Value;
        if (includeValue)
            this.Value = ExtractNativeType(value);
        this.IdType = value?.GetType().FullName();
    }

    readonly int IComparable<IdSnapshotInformation>.CompareTo(IdSnapshotInformation other) => Value?.ToString()?.CompareTo(other.Value?.ToString()) ?? -1;

    /// <returns/>
    public readonly override string ToString() => $"{IdGroupName}.{IdName} = {Value}";


    [return: NotNullIfNotNull("value")]
    private static object? ExtractNativeType(object? value)
        => value switch
        {
            null => null,
            IntValueType vt => vt.Value,
            StringValueType vt => vt.Value,
            GuidValueType vt => vt.Value,
            _ => value
        };
    /// <summary>
    /// The <see cref="DataPackageValues.IdGroupName"/> of this id.
    /// </summary>
    public string IdGroupName { get; set; }
    /// <summary>
    /// The <see cref="DataPackageValues.IdName"/> of this id.
    /// </summary>
    public string IdName { get; set; }
    /// <summary>
    /// The <see cref="ValueType{T}.Value"/> of this id.
    /// </summary>
    public object? Value { get; set; }
    /// <summary>
    /// The <see cref="Type"/>'s <see cref="TypeHelper.FullName(System.Reflection.MethodBase,bool,bool,bool,bool)"/> of this id.
    /// </summary>
    public string? IdType { get; set; }

}