using FluentAssertions;

using JLib.Exceptions;
using JLib.ValueTypes;

using System.Collections.Concurrent;
using System.Linq.Expressions;
using System.Reflection;

using Xunit;

using static JLib.Helper.ExpressionHelper;
using static JLib.ValueTypes.ValueType;

namespace JLib.Helper.Tests;
public class EquivalenceHelperTests
{
    [Fact]
    public void ForNullableClass_BeforeAndNew_ExpressionsAreEquivalent()
    {
        var reason = string.Empty;
        Expression<Func<string?, MyValueType?>> newExpression = FactoryExpressions.ForNullableClass<MyValueType, string>();
        Expression<Func<string?, MyValueType?>> oldExpression = OldForNullableClass<MyValueType, string>();
        ExpressionComparer.AreExpressionsEquivalent(newExpression, newExpression, out reason).Should().BeTrue($"The expressions generated by the 'new' and 'new' ForNullableClass methods are equivalent. <Reason: {reason}>");
        ExpressionComparer.AreExpressionsEquivalent(oldExpression, oldExpression, out reason).Should().BeTrue($"The expressions generated by the 'before' and 'before' ForNullableClass methods are equivalent. <Reason: {reason}>");
        ExpressionComparer.AreExpressionsEquivalent(oldExpression, newExpression, out reason).Should().BeTrue($"The expressions generated by the 'before' and 'new' ForNullableClass methods are equivalent. <Reason: {reason}>");
    }

    // Define a dummy ValueType and test class for the example
    public record MyValueType : ValueType<string>
    {
        public MyValueType(string value) : base(value) { }
    }

    static ConcurrentDictionary<string, LambdaExpression> ExpressionCache = new ConcurrentDictionary<string, LambdaExpression>();
    public static Expression<Func<T?, TVt?>> OldForNullableClass<TVt, T>()
    // note: the name follows a naming scheme and is accessed via non-nameof reflection, therefore the method must not be renamed.
    // said code is located in ForAnyType
    where TVt : ValueType<T>
    where T : class
    => ExpressionCache.GetOrAdd("GetExpressionCacheKey<TVt>(true)", _ =>
    {
        var lambda = FactoryExpressions.ForNonNullableClass<TVt, T>();
        return ((Expression<Func<T?, TVt?>>)(value => value == null ? null : CtorPlaceholder<T, TVt>(value))).ReplaceMethod(PlaceholderMi, lambda);
    }).CastTo<Expression<Func<T?, TVt?>>>();

    private static readonly MethodInfo PlaceholderMi = typeof(EquivalenceHelperTests).GetMethod(nameof(CtorPlaceholder), BindingFlags.Static | BindingFlags.NonPublic)
                                                        ?? throw new InvalidSetupException("Ctor placeholder could not be found");
    private static TVt CtorPlaceholder<T, TVt>(T value)
        where TVt : ValueType<T>
        => throw new InvalidSetupException("this should have been replaced");
}
