using System.Linq.Expressions;
using FluentAssertions;

using static JLib.Helper.ExpressionHelper;

using Xunit;
using static JLib.ValueTypes.ValueType;
using JLib.ValueTypes;

namespace JLib.Helper.Tests;
public class EquivalenceHelperTests
{
    [Fact]
    public void ForNullableClass_BeforeAndNew_ExpressionsAreEquivalent()
    {
        Expression<Func<string?, MyValueType?>> beforeExpression = FactoryExpressions.ForNullableClass<MyValueType, string>();
        Expression<Func<string?, MyValueType?>> newExpression = FactoryExpressions.OldForNullableClass<MyValueType, string>();
        ExpressionComparer.AreExpressionsEquivalent(newExpression, newExpression, out string reason).Should().BeTrue($"The expressions generated by the 'new' and 'new' ForNullableClass methods are equivalent. Reason: {reason}");
        ExpressionComparer.AreExpressionsEquivalent(beforeExpression, beforeExpression, out reason).Should().BeTrue($"The expressions generated by the 'before' and 'before' ForNullableClass methods are equivalent. Reason: {reason}");
        ExpressionComparer.AreExpressionsEquivalent(beforeExpression, newExpression, out reason).Should().BeTrue($"The expressions generated by the 'before' and 'new' ForNullableClass methods are equivalent. Reason: {reason}");
    }

    // Define a dummy ValueType and test class for the example
    public record MyValueType : ValueType<string>
    {
        public MyValueType(string value) : base(value) { }
    }

}
