<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JLib.ValueTypes.Mapping\JLib.ValueTypes.Mapping.csproj" />
    <ProjectReference Include="..\JLib.ValueTypes\JLib.ValueTypes.csproj" />
  </ItemGroup>

</Project>
