<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Provides validated JLib ValueType implementations for file system path segments such as file names, file extensions, directory names, drive letters, and absolute or relative file and directory paths. Built on JLib.ValueTypes to enforce path validity through strongly typed values.</Description>
        <PackageTags>JLib;ValueTypes;filesystem;path;validation;dotnet</PackageTags>
    </PropertyGroup>
    <ItemGroup>
    <ProjectReference Include="..\JLib.ValueTypes\JLib.ValueTypes.csproj" />
  </ItemGroup>

</Project>
