<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Snapshooter.Xunit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\JLib.Reflection\JLib.Reflection.csproj" />
    </ItemGroup>

</Project>

