<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JLib.DataProvider\JLib.DataProvider.csproj" />
    <ProjectReference Include="..\JLib.HotChocolate\JLib.HotChocolate.csproj" />
    <ProjectReference Include="..\JLib.Reflection\JLib.Reflection.csproj" />
  </ItemGroup>

</Project>
