<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\JLib.HotChocolate\JLib.HotChocolate.csproj" />
    <ProjectReference Include="..\JLib.Testing\JLib.Testing.csproj" />
  </ItemGroup>
</Project>
