<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.Data" />
    <PackageReference Include="HotChocolate.Execution" />
    <PackageReference Include="HotChocolate.Execution.Abstractions" />
    <PackageReference Include="HotChocolate.Types" />
      <!--used for GetOneDataObjectAsync-->
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <!--<PackageReference Include="Microsoft.EntityFrameworkCore" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JLib.DataProvider\JLib.DataProvider.csproj" />
  </ItemGroup>

</Project>

